
export const currencyDetails: Record<string, { name: string; flag: string }> = {
  USD: { name: "US Dollar", flag: "🇺🇸" },
  EUR: { name: "Euro", flag: "🇪🇺" },
  JPY: { name: "Japanese Yen", flag: "🇯🇵" },
  GBP: { name: "British Pound", flag: "🇬🇧" },
  AUD: { name: "Australian Dollar", flag: "🇦🇺" },
  CAD: { name: "Canadian Dollar", flag: "🇨🇦" },
  CHF: { name: "Swiss Franc", flag: "🇨🇭" },
  CNY: { name: "Chinese Yuan", flag: "🇨🇳" },
  INR: { name: "Indian Rupee", flag: "🇮🇳" },
  BRL: { name: "Brazilian Real", flag: "🇧🇷" },
  RUB: { name: "Russian Ruble", flag: "🇷🇺" },
  ZAR: { name: "South African Rand", flag: "🇿🇦" },
  SGD: { name: "Singapore Dollar", flag: "🇸🇬" },
  NZD: { name: "New Zealand Dollar", flag: "🇳🇿" },
  MXN: { name: "Mexican Peso", flag: "🇲🇽" },
  HKD: { name: "Hong Kong Dollar", flag: "🇭🇰" },
  NOK: { name: "Norwegian Krone", flag: "🇳🇴" },
  SEK: { name: "Swedish Krona", flag: "🇸🇪" },
  KRW: { name: "South Korean Won", flag: "🇰🇷" },
  TRY: { name: "Turkish Lira", flag: "🇹🇷" },
  IDR: { name: "Indonesian Rupiah", flag: "🇮🇩" },
  MYR: { name: "Malaysian Ringgit", flag: "🇲🇾" },
  PHP: { name: "Philippine Peso", flag: "🇵🇭" },
  THB: { name: "Thai Baht", flag: "🇹🇭" },
  VND: { name: "Vietnamese Dong", flag: "🇻🇳" },
  PLN: { name: "Polish Złoty", flag: "🇵🇱" },
  CZK: { name: "Czech Koruna", flag: "🇨🇿" },
  HUF: { name: "Hungarian Forint", flag: "🇭🇺" },
  ILS: { name: "Israeli New Shekel", flag: "🇮🇱" },
  DKK: { name: "Danish Krone", flag: "🇩🇰" },
  // Gulf Currencies
  SAR: { name: "Saudi Riyal", flag: "🇸🇦" },
  AED: { name: "UAE Dirham", flag: "🇦🇪" },
  QAR: { name: "Qatari Riyal", flag: "🇶🇦" },
  KWD: { name: "Kuwaiti Dinar", flag: "🇰🇼" },
  BHD: { name: "Bahraini Dinar", flag: "🇧🇭" },
  OMR: { name: "Omani Rial", flag: "🇴🇲" },
};
